import 'package:hoa12_dulich/danhmuc_model/danhmuc_amthuc.dart';

class KhothongtinAmthuc {
  static List<danhmucAmthuc> DanhmucAmthuc = [
    danhmucAmthuc(
      title: "Bánh bột lọc",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình bánh ngon nhất",
      image: "assets/banhbotloc.jpg",
      introduction: "Quảng Bình không phải là quê hương của chiếc bánh bột lọc, nhưng bánh bột lọc là một trong những món ăn vặt yêu thích của người Quảng Bình. Bánh bột lọc trông bên ngoài không có gì đặc biệt nhưng người dân ở đây đã chế biến và nêm nếm để tạo ra hương vị rất đặc biệt. Khi vắt vỏ bánh, không nên quá mỏng hoặc quá dày, cho phần nhân vào giữa vỏ bánh rồi khéo léo dùng tay miết nhẹ, sau đó gói lại bằng lá chuối để tạo vị thơm đặc trưng. Ăn một miếng bánh sẽ cảm nhận vị dai dai mềm mềm của bột lọc, vị đậm đà của nhân tôm thịt, măng hoặc mộc nhĩ hoà quyện cùng vị nước mắm cay ngọt đã làm say lòng biết bao thực khách.",
      quan1: "Bánh bột lọc mệ Xuân",
      address1: "15 Lê Thành Đồng, Đồng Hới, Quảng Bình",
      sodienthoai1: "0913.011.013",
      quan2: "Bánh bột lọc Hương Hoài",
      address2: "1 Lê Thành Đồng, Đồng Hới, Quảng Bình",
      sodienthoai2: "0383.618.818",
    ),
    danhmucAmthuc(
      title: "Bánh xèo Quảng Hoà ",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình bánh ngon nhì",
      image: "assets/banhxeoquanghoa.jpg",
      introduction: "Nhắc đến món bánh xèo, nhiều người thường nghĩ tới bánh xèo Quảng Hoà, nơi nổi tiếng với những chiếc bánh xèo thơm ngon. Bánh xèo Quảng Hoà chọn gạo lức làm nguyên liệu chính, bởi gạo lức tạo nên mùi vị và màu sắc rất riêng trong bánh. Một điểm độc đáo nữa là bánh xèo gạo lức không hề không hề có nhân bên trong.  Khi ăn cuốn bánh cùng lá đinh lăng, giá đậu đỏ và chấm với nước mắm chua cay ngọt tạo nên hương vị cực kỳ hấp dẫn, bạn sẽ cảm nhận được vị ngọt, dẻo, dai của bánh. Nhất định sẽ khiến bạn ăn đến căng bụng, ăn một lần là lại muốn ăn lần nữa.",
      quan1: "Quán Dì Nhung",
      address1: "thôn Thanh Tân, xã Quảng Hòa, Quảng Trạch, Quảng Bình",
      sodienthoai1: "0916.657.405",
      quan2: "Quán O Hương",
      address2: "xã Quảng Hòa, Quảng Trạch, Quảng Bình",
      sodienthoai2: "0336.984.010",
    ),
    danhmucAmthuc(
      title: "Bánh bèo ",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình bánh ngon ba",
      image: "assets/banhbeo.jpg",
      introduction: "Bánh bèo là một trong những món ăn truyền thống của người dân Quảng Bình, được làm từ bột gạo, ăn kèm với nước mắm ngọt, mùi vị mặn ngọt vừa phải. Món ăn hấp dẫn với màu trắng của bột gạo, màu vàng rộm của tôm cháy cùng chén nước mắm ngọt cay xé lưỡi bất kể là màu sắc hay là mùi vị đều có thể nói là đúng chất Quảng Bình. Ăn bánh bèo phải từ từ mới cảm nhận hết được cái thơm ngon của nó. Vị ngọt của tôm cháy, cái đậm đà cay nồng của nước mắm hòa quyện với những chiếc bánh bèo thơm ngon sự trải nghiệm vị giác đặc biệt này khiến các du khách đã từng nếm thử bánh bèo cho dù sau này xa Quảng Bình cũng không thể nào quên được mùi vị của xứ Quảng.",
      quan1: "Quán Cô Vân",
      address1: "80 Lê Thành Đồng, Đồng Hới, Quảng Bình",
      sodienthoai1: "0232.3717.999",
      quan2: "Quán bánh bèo Anh Đào",
      address2: "11 Đồng Lực, Đồng Hới, Quảng Bình",
      sodienthoai2: "0968.815.857",
    ),
    danhmucAmthuc(
      title: "Bánh khoái",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình bánh ngon tư",
      image: "assets/banhkhoai.jpg",
      introduction: "Bánh khoái là món ăn có nguồn gốc từ xứ Huế. Thế nhưng bánh khoái lại là món ăn quen thuộc và khoái khẩu của người dân Quảng Bình. Món bánh khoái với cách chế biến hoàn toàn độc đáo, đã để lại ấn tượng với nhiều thực khách khi thưởng thức. Bánh khoái được làm từ tôm, thịt heo, hành tây, giá, mộc nhĩ, trứng gà và bột gạo nhưng bánh khoái tại thành phố Đồng Hới mang nhiều nét rất đặc biệt. Chiếc bánh sau khi đổ xong có màu vàng tươi, giòn tan, thơm ngon được ăn cùng chén nước chấm được pha chế công phu, có vị chua chua ngọt ngọt cay cay, vị đậm đà của nước mắm ngon, bánh được ăn kèm với các loại rau thơm và dưa chuột thái mỏng, nước mắm chua ngọt…. mang đến cho người ăn cảm nhận được hương vị đặc trưng không lẫn vào đâu được.",
      quan1: "Quán Cô Năm",
      address1: "13 đường Trần Hưng Đạo, Đồng Hới, Quảng Bình",
      sodienthoai1: "0385.704.219",
      quan2: "Quán Ly Ly",
      address2: "11A đường Cô Tám, Đồng Hới, Quảng Bình",
      sodienthoai2: "0911.027.373",
    ),
    danhmucAmthuc(
      title: "Bánh cuốn tôm ",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình bánh ngon năm",
      image: "assets/banhcuontom.jpg",
      introduction: "Nhắc đến các món ăn sáng ở Quảng Bình, không thể khống nhắc đến món bánh cuốn tôm, một món ăn đặc trưng của Quảng Bình. Loại bánh này được làm bằng loại gạo ngon, xay gạo thành bột rồi cho bột vào ngâm nước khoảng 3-5 tiếng. Sau khi đun nóng nước trong nồi, quấy bột đều lên rồi múc một lượng bột vừa phải cho lên lớp vải tráng bánh cuốn thì trở thành từng miếng bột mỏng hình tròn. Bánh được cuốn lại thành những thanh dài, rắc tôm chấy lên trên mặt bánh. Món ăn kèm dưa chuột thái mỏng và các loại rau thơm, nước mắm chua ngọt. Mặc dù khá đơn giản nhưng đây là một trong những món ăn nổi tiếng tại địa phương này.",
      quan1: "Quán bánh Tứ Quý",
      address1: "63 đường Trương Pháp, Đồng Hới, Quảng Bình",
      sodienthoai1: "02323.821.371",
      quan2: "Nghệ sỹ Quán",
      address2: "đường Phạm Văn Đồng, Đồng Hới, Quảng Bình",
      sodienthoai2: "0908.228.199",
    ),
    danhmucAmthuc(
      title: "Cháo bánh canh ",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình cháo ngon nhất",
      image: "assets/chaobanhcanh.jpg",
      introduction: "Nói đến cháo canh, là nói đến món ăn được yêu thích của người dân Quảng Bình. Nó quá đỗi quen thuộc, quen thuộc tới mức trở thành một món ăn mang đặc sản quê hương, không ít thực khách ăn một lần nhớ mãi không quên. Sợi bánh canh được làm từ bột gạo, bột lọc hoặc bột mì, được nấu cùng với nước dùng xương heo, cá, tôm, ghẹ, rạm, bỏ thêm rau thơm, rắc thêm chút hạt tiêu. Thưởng thức bát cháo canh Quảng Bình, thực khách sẽ dễ dàng cảm nhận được hương thơm ngào ngạt của nước dùng, từng sợi bánh canh dai, giòn, vị béo của ram, những miếng cá vàng ươm hấp dẫn,  chắc chắn bạn sẽ không khỏi xuýt xoa bởi sự thơm ngon, lạ miệng của món đặc sản này.",
      quan1: "Quán cháo canh Huyền Nhân",
      address1: "129 Lý Thái Tổ, Đồng Sơn, Đồng Hới, Quảng Bình",
      sodienthoai1: "01677.099.386",
      quan2: "Quán cháo canh Sương Hồng",
      address2: "38 Nguyễn Trãi, Đồng Hới, Quảng Bình",
      sodienthoai2: "0905.364.977",
    ),
    danhmucAmthuc(
      title: "Bún bò giò heo",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình bún ngon nhất",
      image: "assets/bunbogioheo.jpg",
      introduction: "Bún bò giò heo là món ăn nổi tiếng có nguồn gốc từ Huế. Với sự kết hợp hoàn hảo của nhiều hương vị như vị đậm đà của nước cốt xương heo, cho thêm sợi bún và miếng giò heo, tiết heo, thịt bò, chả cua …vị cay cay xuýt xoa của ớt đỏ, vị chua thanh của chanh tươi, còn ăn kèm với một dĩa rau tươi ngon gồm húng quế, bạc hà, rau mùi và giá đỗ xanh, mùi thơm nồng đượm. Mỗi tô bún đều mang đến sự hòa quyện vừa miệng, trông thật hấp dẫn và đầy đặn, kích thích cảm giác ngon miệng ngay từ cái nhìn đầu tiên, thỏa mãn trọn vẹn vị giác của thực khách.",
      quan1: "Quán Phong Phú",
      address1: "83 Hữu Nghị, Đồng Hới, Quảng Bình",
      sodienthoai1: "0914.749.732",
      quan2: "Quán Cố Đô",
      address2: "171 Hai Bà Trưng, Đồng Hới, Quảng Bình",
      sodienthoai2: "0902.686.112",
    ),
    danhmucAmthuc(
      title: "Cháo hàu",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình cháo ngon nhì",
      image: "assets/chaohau.jpg",
      introduction: "Cháo hàu huyện Quán Hàu thơm ngon nức tiếng gần xa. Do nguồn nước nên những con hàu sữa nơi đây béo ngậy và thơm ngon, mang lại nguồn dinh dưỡng tuyệt vời. Du lịch thành phố Đồng Hới, được thưởng thức tô cháo hàu nóng hổi tuyệt ngon, vị béo của hàu, vị ngọt của nấm rơm, vị cay của hạt tiêu, hành, hoà quyện cùng vị mềm dẻo của hạt gạo thơm đánh thức vị giác. Nếu một lần được thưởng thức món cháo hàu huyện Quán Hàu chắc chắn sẽ không thể nào quên.",
      quan1: "Quán cháu hàu O Mai",
      address1: "ngã 3 đường Quang Trung, Quán Hàu, Quảng Ninh, Quảng Bình",
      sodienthoai1: "0354.535.993",
      quan2: "Quán cháo hàu Thùy Dương",
      address2: "15 Phan Bội Châu, Đồng Hới, Quảng Bình",
      sodienthoai2: "0904.250.376",
    ),
    danhmucAmthuc(
      title: "Cháo lươn đồng",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình cháo ngon ba",
      image: "assets/chaoluondong.jpg",
      introduction: "Cháo lươn đồng là món ăn nổi tiếng của xứ Nghệ. Thế nhưng nói đến ẩm thực ở Quảng Bình thì không thể không nhắc đến món lươn. Cháo lươn, miến lươn, súp lươn và các món ăn Quảng Bình khác với nguyên liệu là lươn được thực khách rất ưa chuộng. Lươn vàng hay còn gọi là lươn đồng, thịt không chỉ mềm, thơm ngon mà còn có giá trị dinh dưỡng cao. Cháo lươn là món ăn ngon và bổ dưỡng. thưởng thức tô cháo lươn nóng hổi tuyệt ngon, vị ngọt của lươn, vị thơm của củ nén, vị cay của tiêu ớt, hành, lá tía tô, hoà quyện cùng vị mềm dẻo của hạt gạo thơm đánh thức vị giác. Nếu một lần được thưởng thức món cháo lươn chắc chắn sẽ không thể nào quên.",
      quan1: "Cháo lươn chị Ngạnh",
      address1: "18 Hoàng Diệu, Đồng Hới, Quảng Bình",
      sodienthoai1: "0904.624.046",
      quan2: "Cháo lươn Thùy Dương",
      address2: "15 Phan Bội Châu, Đồng Hới, Quảng Bình",
      sodienthoai2: "0904.250.376",
    ),
    danhmucAmthuc(
      title: "Hải sản tươi sống",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình hải sản ngon nhất",
      image: "assets/haisantuoisong.jpg",
      introduction: "Đến với Quảng Bình, du khách có rất nhiều lựa chọn cho thực đơn hấp dẫn để thưởng thức những món hải sản thơm ngon và độc đáo. Hải sản ở đây rất phong phú, chủng loại đầy đủ. Một đặc điểm nổi bật khác của đồ ăn ở đây là có màu sắc và hương vị, người Quảng Bình đặc biệt thích dùng gia vị nên các món ăn họ làm ra đều rất thơm ngon. Buổi chiều tối rất nhiều quán hải sản dọc đường lớn bên bờ biển mở ra cả dãy, đều bán hải sản tươi sống như: tôm hùm, mực, cua biển, nghao, hàu, ốc hương, sò huyết, cá nục, cá ngừ… Các loại hải sản được bỏ lên bếp than nướng hoặc hấp chín, cho thêm chút gia vị, mùi thơm nức mũi. Được ngồi bên bãi biển hóng gió, nghe tiếng sõng vỗ, ăn hải sản cùng bạn bè và người thân, thật là tuyệt vời.",
      quan1: "Nhà hàng hải sản Mệ Toại",
      address1: "số 185 Trương Pháp, phường Hải Thành, Đồng Hới, Quảng Bình ",
      sodienthoai1: "0909.814.027",
      quan2: "Nhà hàng nổi Bình Minh ",
      address2: "Phú Hải, Đồng Hới, Quảng Bình",
      sodienthoai2: "0833. 237. 777",
    ),
    danhmucAmthuc(
      title: "Khoai Deo",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình khoai ngon nhất",
      image: "assets/khoaigieo.jpg",
      introduction: "Vùng đất biển cát trắng Hải Ninh, Quảng Bình là vùng đất có truyền thống lâu năm về trồng khoai để làm khoai Deo. Khoai Deo được làm từ những củ khoai lang tươi ngon được nấu chín, thái lát và phơi khô tự nhiên. Mảnh đất cát trắng và cái nắng chang chang của mảnh đất này lại là một lợi thế, và rất thích hợp để trồng khoai lang. Khoai Deo Hải Ninh nổi tiếng khắp ba miền bởi hương vị thơm ngon hảo hạng mà hiếm có loại khoai Deo nào sánh bằng. Khoai Deo ở đây có mùi vị rất đặc trưng, thơm phưng phức, dẻo ngọt và nhiều dưỡng chất. Khoai Deo Hải Ninh, Quảng Bình là món quà quê giản dị gửi tặng bạn bè, người thân. Là món ăn vặt bình dị chân chất đậm đà hương vị miền quê, nhưng khoai deo đã làm cho những ai một lần nếm thử cũng phải nhung nhớ mãi về sau.",
      quan1: "Khoai deo Linh Huệ",
      address1: "46 Trường Chinh, Bắc Lý, thành phố Đồng Hới, Quảng Bình.",
      sodienthoai1: "0919.075.822",
      quan2: "Khoai deo Hải Ninh",
      address2: "178 Nguyễn Văn Cừ, thành phố Đồng Hới, Quảng Bình",
      sodienthoai2: "0979.453.416",
    ),
    danhmucAmthuc(
      title: "Cá trắm sông Son",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình cá ngon nhất",
      image: "assets/catramsongson.jpg",
      introduction: "Dòng sông Son với làn nước trong xanh màu ngọc bích tuyệt đẹp bắt nguồn từ các khe suối trong khu vực Phong Nha - Kẻ Bàng. Tại đây có một làng nghề nuôi cá lồng lâu năm của người dân Phong Nha. Cá trắm thì nơi nào cũng có. Nhưng không phải nơi nào cũng có hương vị thơm ngon như cá trắm Sông Son. Thức ăn chính của cá là rong tảo, phù du nên thịt cá rất thơm ngon, bổ dưỡng.Cá trắm sông Son được xem là biểu tượng ẩm thực của vùng di sản Phong Nha và đặc biệt là đặc sản mang thương hiệu du lịch Quảng Bình, vị ngọt thơm từ thịt cá mang đến cho du khách những trải nghiệm vị giác hấp dẫn, mới lạ, và đầy bổ dưỡng.Dưới bàn tay khéo léo và khẩu vị tinh tế của người dân địa phương, những con cá trắm được chế biến thành rất nhiều các món ngon như: cá trắm kho củ riềng, cá trắm nướng lá chuối, cá trắm um măng dưa, cá trắm rang muối, cá trắm hấp tiêu chanh, cá trắm sốt chanh dây, cơm chiên chả cá, bún chả cá ăn kèm rau sống và nước mắm chua ngọt. Đặc biệt là món cá trắm um măng dưa có hương vị đậm đà, chua cay sẽ khiến bạn thích thú và nhớ mãi.",
      quan1: "Nhà hàng tại Chày Lập Farmstay - làng Chày",
      address1: "làng Chày, Bố Trạch, Quảng Bình",
      sodienthoai1: "000932 488 839",
      quan2: "Nhà Hàng Thu Huế",
      address2: "thị trấn Phong Nha, Bố Trạch,  Quảng Bình",
      sodienthoai2: "0945 536 797",
    ),
    danhmucAmthuc(
      title: "Ram đẻn",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình cá ngon nhất",
      image: "assets/ramden.jpg",
      introduction: "Đẻn là một loại rắn biển, thân nhỏ, mình có vảy và dài khoảng 1 - 2m. Mặc dù có vẻ ngoài khá đáng sợ với nhiều người nhưng thực chất, đẻn biển là loài mang lại giá trị dinh dưỡng cao. Đến Quảng Bình, du khách sẽ được thưởng thức đặc sản ram đẻn - một trong những món ngon được chế biến từ loài động vật này. Về hình thức, ram đẻn biển trông rất giống với cây chả giò của người miền Nam, tuy nhiên quá trình sơ chế và thực hiện thì cầu kỳ, công phu hơn. Quan trọng nhất phải kể đến bước làm sạch đẻn biển. đẻn biển được nhúng trong nước sôi để cạo sạch vảy rồi mới mang đi mổ bụng và cắt bỏ phần đầu, ruột, da trên sống lưng… Sau khi đã sơ chế sạch sẽ, đẻn biển được băm nhuyễn cùng gia vị rồi để một lúc cho ngấm. Sau khi đẻn biển đã thấm đều gia vị, người ta sẽ cuốn lại thành những chiếc ram nhỏ, đem chiên giòn trong dầu nóng. Ram đẻn chín tới không chỉ có mùi thơm hấp dẫn mà còn vàng ươm, giòn rụm. Món này thường ăn khi còn nóng, kết hợp với rau sống, bánh tráng và chấm cùng với nước mắm chua cay.",
      quan1: "Nhà hàng hải sản Mệ Toại",
      address1: "số 185 Trương Pháp,  Hải Thành, thành phố Đồng Hới, Quảng Bình ",
      sodienthoai1: "0909.814.027",
      quan2: "Nhà hàng nổi Bình Minh ",
      address2: "Phú Hải, Đồng Hới, Quang Binh ",
      sodienthoai2: "0833. 237. 777",
    ),
    danhmucAmthuc(
      title: "Cua om bí đao",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình cua ngon nhất",
      image: "assets/cuaombidao.jpg",
      introduction: "Cua om bí đao là  một món ngon dùng nguyên liệu hải sản ở vùng biển Quảng Bình. Đây thực sự là một món ăn ngon có thể giải nhiệt trong mùa hè nóng bức. Vị tươi ngon của bí đao và vị ngọt của cua biển kết hợp mang đến một hương vị mới lạ và để lại ấn tượng khó quên cho những ai có dịp nếm thử món ăn này. Cua biển làm sạch để ráo. Bí đao gọt vỏ, xắt nhỏ. Tỏi, hành tím băm nhỏ. Phi thơm tỏi hành tím rồi cho cua biển vào, đảo trên lửa lớn, cho chút nước sôi rồi nêm những gia vị ở trên vào tiếp đó cho bí đao vào đậy nắp lại đến khi chín rồi bỏ thêm hành lá, ngò, rau quế cắt nhỏ. Cua om bí đao nước ngọt, thơm, hương vị hoà quyện rất ngon.",
      quan1: "Nhà hàng nổi Bình Minh ",
      address1: "Phú Hải, Đồng Hới, Quảng Bình",
      sodienthoai1: "0833. 237. 777",
      quan2: "Nhà hàng nổi Nam Thành ",
      address2: "Phú Hải, Đồng Hới, Quảng Bình",
      sodienthoai2: "0904.624.086",
    ),
    danhmucAmthuc(
      title: "Mực một nắng",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình cua ngon nhất",
      image: "assets/mucmotnang.jpg",
      introduction: "Mực một nắng Quảng Bình là một loại hải sản đặc biệt, được chế biến từ mực tươi sau khi rửa sạch với nước biển, đem phơi nắng gắt cho khô, chỉ phơi một lần nên mực vẫn mềm và giòn, đặc biệt ở vùng biển càng mặn thì mực càng ngon, nhất là ở miền trung và mặn nhất là Quảng Bình. Có nhiều loại mực một nắng nhưng mực một nắng Quảng Bình ngon nhất được làm từ mực lá hoặc mực ống bởi thịt dày và ngọt hơn các loại mực khác.Sở dĩ có tên gọi là “Mực một nắng” là vì con mực tươi làm sạch và được phơi chỉ 1 nắng trong ngày, mực một nắng là loại mực nguyên chất được phơi khô một nắng, mực sau khi đánh bắt nếu số lượng ít bà con sẽ rửa sạch bằng nước biển và phơi ngay trên thuyền.Những ngày trúng vụ mùa, nhiều mực sẽ rửa sạch mang mang về phơi khô trên giàn thép, chọn nắng phơi mực 1 nắng phải đúng “chuẩn” phải là nắng to gắt, càng nắng thì mực càng ngon, quan trọng là chỉ có đủ nắng, nếu đúng mùa kết hợp với gió Lào thì quá tuyệt vời.",
      quan1: "Quán hải sản Dì Hà",
      address1: "Quang Phú, Đồng Hới, Quảng Bình",
      sodienthoai1: "0985.742.334",
      quan2: "Nhà hàng hải sản Mệ Toại",
      address2: "số 185 Trương Pháp, Hải Thành, Đồng Hới, Quảng Bình ",
      sodienthoai2: "0909.814.027",
    ),
  ];
}