import 'package:hoa12_dulich/danhmuc_model/danhmuc_ditich.dart';

class KhothongtinDitich {
  static List<danhmucDitich> DanhmucDitich = [
    danhmucDitich(
      title: "Quảng Bình Quan",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình cổng chào có ý nghĩa nhất",
      image: "assets/quangbinhquan.jpg",
      introduction: "Quảng Bình Quan là một cổng án ngữ của thành cổ Quảng Bình thuộc phường Hải Đình, nằm ở trung tâm thành phố Đồng Hới, tỉnh Quảng Bình. Quảng Bình Quan là một trong ba cửa ải của luỹ Trấn Ninh, từ chân núi Đầu Mâu đến cửa biển Nhật Lệ do nhà chiến lược quân sự tài ba Đào Duy Từ thiết kế và xây đắp cùng lúc với chiến luỹ vào năm khoảng những năm 1631, trong cuộc nội chiến khốc liệt giữa hai thế lực Trịnh - Nguyễn kéo dài gần hai thế kỷ tương tàn.",
      address: "Đồng Hải, Đồng Hới, Quảng Bình",
      vitrimap: "Toạ độ google map: 17.463306, 106.623972",
    ),
    danhmucDitich(
      title: "Quảng trường Hồ Chí Minh",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình quảng trường đẹp nhất",
      image: "assets/quangtruonghcm.jpg",
      introduction: "Quảng Trường Hồ Chí Minh nằm ở đường Hùng Vương, phường Đồng Hải, thành phố Đồng Hới, Quảng Bình. Đây là công trình thể hiện tình cảm tri ân sâu sắc của nhân dân Quảng Bình đối với công lao to lớn của Bác Hồ kính yêu và các anh hùng liệt sĩ. Quảng Trường Hồ Chí Minh có diện tích 6,8 ha với các hạng mục gồm: Tượng đài Chủ tịch Hồ Chí Minh và nhân dân tỉnh Quảng Bình, khu quảng trường, sân hành lễ, đường diễu hành, cây xanh, thảm cỏ… Phía trong khuôn viên quần thể Quảng trường là đền thờ Bác Hồ và các Anh hùng liệt sĩ. Công trình xây dựng theo lối kiến trúc mái đình làng Việt cổ, có tháp chuông, tháp bia ghi lại lời căn dặn của Bác Hồ với quân và dân Quảng Bình ngày Bác về thăm (16-6-1957).",
      address: "Đồng Hải, Đồng Hới, Quảng Bình ",
      vitrimap: "Toạ độ google map: 17.468001, 106.622181",
    ),
    danhmucDitich(
      title: "Lăng mộ Đại tướng Võ Nguyên Giáp",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình lăng mộ đẹp nhất",
      image: "assets/langdaituong.jpg",
      introduction: "Vũng Chùa - Đảo Yến nơi an nghỉ của Đại tướng Võ Nguyên Giáp, vị Đại tướng huyền thoại của dân tộc Việt Nam. Thuộc thôn Thọ Sơn; xã Quảng Đông; huyện Quảng Trạch (Quảng Bình), với thế “rồng cuộn hổ ngồi”. Mộ Đại tướng, lưng tựa dãy núi Trường Sơn hùng vĩ, mặt hướng ra biển Đông bao la rộng lớn; một vị thế đắc địa có một không hai. Vũng Chùa - Đảo Yến, một thắng cảnh nằm trong vịnh Hòn La, được bao bọc bởi đảo Hòn La, Hòn Gió, Hòn Nồm. Đảo Yến với diện tích khoảng 10ha, là nơi sinh sống của nhiều chim én nhất ở tỉnh Quảng Bình. Đứng trên đảo phóng tầm mắt ra xa, Vũng Chùa là bãi biển xinh đẹp với bờ cát trắng trải dài, sự hòa quyện giữa núi non, biển đảo xinh đẹp đã tạo nên nơi đây một bức tranh phong cảnh hữu tình. Vũng Chùa - Đảo Yến là điểm du lịch tâm linh hấp dẫn du khách trong và ngoài nước đến khám phá.",
      address: "Quảng Đông, Quảng Trạch, Quảng Bình",
      vitrimap: "Toạ độ google map: 17.923944, 106.494083",
    ),
    danhmucDitich(
      title: "Hang Đại tướng Võ Nguyên Giáp ",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình hang động đẹp nhất",
      image: "assets/hangdaituong.jpg",
      introduction: "Hang Đại tướng Võ Nguyên Giáp nằm giữa dãy núi Trường Sơn hùng vĩ thuộc xã Ngân Thuỷ, Lệ Thủy, Quảng Bình. Hang Đại tướng được đưa vào khai thác du lịch đầu năm 2019. Người dân tộc Vân Kiều  thường gọi là hang Đại tướng hoặc hang Ông Giáp vì những năm 1971 – 1973, Đại tướng Võ Nguyên Giáp dùng hang này để sinh sống, chỉ huy các chiến dịch ở mặt trận phía Nam. Đến đây bạn có thể chiêm ngưỡng vẻ đẹp kỳ vĩ của những khối thạch nhũ, măng đá độc đáo bên trong hang của hệ thống hang động Võ Nguyên Giáp.",
      address: "Ngân Thủy, Lệ Thủy, Quảng Bình",
      vitrimap: "Toạ độ google map: 17.194000, 106.604389",
    ),
    danhmucDitich(
      title: "Hang Tám Cô",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình hang dộng đẹp sáu",
      image: "assets/hangtamco.jpg",
      introduction: "Hang Tám Cô nằm trên đường 20 Quyết Thắng thuộc xã Tân Trạch huyện Bố Trạch tỉnh Quảng Bình, một phần của đường Trường Sơn huyền thoại, nằm sâu trong dãy núi Trường Sơn. Con đường này là “con đường chiến lược”  được mở ra để chi viện cho miền Nam đánh Mỹ . Hang Tám Cô, tám cô gái còn rất trẻ đã cống hiến tuổi thanh xuân của mình cho độc lập, tự do và hòa bình của Tổ quốc. Tên tuổi của họ sẽ mãi mãi đi cùng non sông đất nước, mãi là biểu tượng sáng ngời của chủ nghĩa anh hùng cách mạng Việt Nam. Hang Tám Cô là địa điểm tham quan tâm linh, thu hút lượng lớn du khách đến thăm hằng năm.",
      address: "Tân Trạch, Bố Trạch, Quảng Bình ",
      vitrimap: "Toạ độ google map:  17.502556, 106.260194",
    ),
    danhmucDitich(
      title: "Tượng đài Mẹ Suốt",
      date: "2023/09/19",
      location: "Quảng Bình",
      locationCap: "Quảng Bình tượng đài đẹp nhất",
      image: "assets/tuongdaimesuot.jpg",
      introduction: "Tượng đài Mẹ Suốt nằm bên bờ sông Nhật Lệ xinh đẹp thuộc phường Hải Đinh, thành phố Đồng Hới. Tượng đài Mẹ Suốt được khánh thành năm 2003 vào dịp cả nước ta mừng lễ Quốc khánh 2-9，với chiều cao 7m, tượng đài cách bến đò xưa khoảng hơn 50m.Mẹ Suốt là hình ảnh tiêu biểu của tinh thần dũng cảm của dân tộc Việt Nam.  Bến đò mẹ chèo năm xưa đã trở thành một Di tích lịch sử tiêu biểu ở Đồng Hới trong thời kỳ chống Mỹ với tên gọi thân thương và kính trọng: Bến đò mẹ Suốt. Cạnh dòng Nhật Lệ xinh tươi hiền hoà, ngay giữa trung tâm của bến đò mẹ chèo ngày xưa, Tượng đài Mẹ Suốt được xây dựng uy nghi hoành tráng không chỉ mang giá trị nghệ thuật mà còn phản ánh trọn vẹn bản lĩnh anh hùng, tinh thần bất khuất, ý chí kiên cường và phẩm chất tốt đẹp của người phụ nữ Việt Nam. Tượng đài Mẹ Suốt là công trình văn hóa để lại nhiều cảm xúc và ấn tượng về Quảng Bình cho mỗi du khách khi ghé thăm nơi này.",
      address: "Đồng Hải, Đồng Hới, Quảng Bình",
      vitrimap: "Toạ độ google map: 17.465500, 106.627111",
    ),
  ];
}